// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// templates/index.templ
func IndexPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Go + Templ + Tailwind + HTMX</title><link rel=\"stylesheet\" href=\"/static/css/style.css\"><script src=\"https://unpkg.com/htmx.org@1.9.2\"></script></head><body class=\"bg-gradient-to-r from-green-100 via-green-200 to-green-300 min-h-screen flex items-center justify-center\"><div class=\"bg-white rounded-2xl shadow-xl p-10 max-w-lg w-full text-center space-y-6\"><h1 class=\"text-4xl font-bold text-green-700 mb-4\">Go ✨ Templ ⚡ Tailwind 💨 HTMX 🚀</h1><p class=\"text-gray-600\">Welcome to your starter stack! 🎉</p><div class=\"space-y-4\"><button class=\"bg-green-500 hover:bg-green-600 text-white px-4 py-2 rounded-lg transition\" hx-get=\"/greet\" hx-target=\"#response\" hx-swap=\"innerHTML\">Say Hello 👋</button><div id=\"response\" class=\"text-lg text-green-700 font-semibold\"></div></div><div class=\"pt-4 border-t text-sm text-gray-400\">Hot reload test — try editing <code>index.templ</code>!</div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
